/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as AiReceptionistRouteImport } from './routes/ai-receptionist'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReceptionistRoute = AiReceptionistRouteImport.update({
  id: '/ai-receptionist',
  path: '/ai-receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropertiesRoute,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/$leadId',
  path: '/$leadId',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/conversations': typeof ConversationsRoute
  '/leads': typeof LeadsRouteWithChildren
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/conversations': typeof ConversationsRoute
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/leads': typeof LeadsIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/conversations': typeof ConversationsRoute
  '/leads': typeof LeadsRouteWithChildren
  '/overview': typeof OverviewRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/ai-receptionist'
    | '/conversations'
    | '/leads'
    | '/overview'
    | '/pipeline'
    | '/properties'
    | '/settings'
    | '/team'
    | '/uploads'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/leads/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/ai-receptionist'
    | '/conversations'
    | '/overview'
    | '/pipeline'
    | '/settings'
    | '/team'
    | '/uploads'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/leads'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/ai-receptionist'
    | '/conversations'
    | '/leads'
    | '/overview'
    | '/pipeline'
    | '/properties'
    | '/settings'
    | '/team'
    | '/uploads'
    | '/leads/$leadId'
    | '/properties/$propertyId'
    | '/leads/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiReceptionistRoute: typeof AiReceptionistRoute
  ConversationsRoute: typeof ConversationsRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  PipelineRoute: typeof PipelineRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-receptionist': {
      id: '/ai-receptionist'
      path: '/ai-receptionist'
      fullPath: '/ai-receptionist'
      preLoaderRoute: typeof AiReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface PropertiesRouteChildren {
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiReceptionistRoute: AiReceptionistRoute,
  ConversationsRoute: ConversationsRoute,
  LeadsRoute: LeadsRouteWithChildren,
  OverviewRoute: OverviewRoute,
  PipelineRoute: PipelineRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
